const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://img.etimg.com/thumb/msid-72104862,width-640,resizemode-4,imgsize-274994/italian-food-hallmark-of-quality.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'dinner',
      price: 13.99,
      img: 'https://static.toiimg.com/thumb/53110049.cms?width=1200&height=900',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://i.ytimg.com/vi/SO56AKM8yNk/maxresdefault.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://static.toiimg.com/photo/msid-73190225/73190225.jpg?864644',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'dinner',
      price: 22.99,
      img: 'https://www.healthkart.com/connect/wp-content/uploads/2020/09/1_11.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/02/breakfast-recipes-500x500.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://www.vegrecipesofindia.com/wp-content/uploads/2021/06/idli-recipe-4.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'dinner',
      price: 12.99,
      img: 'https://resize.indiatvnews.com/en/resize/newbucket/715_-/2018/11/food-trends-freakshakes-giant-milkshakes-1542087241.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://www.thenewsminute.com/sites/default/files/styles/news_detail/public/South%20breakfast.jpg?itok=WSVc0C32',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;